services:
  postgres-db:
    container_name: healthapp
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthapp
    ports:
      - "5432:5432"