CREATE TABLE goals
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    calorie_goal DOUBLE PRECISION                        NOT NULL,
    protein_goal DOUBLE PRECISION                        NOT NULL,
    fat_goal     DOUBLE PRECISION                        NOT NULL,
    sat_fat_goal DOUBLE PRECISION                        NOT NULL,
    carb_goal    DOUBLE PRECISION                        NOT NULL,
    sugar_goal   DOUBLE PRECISION                        NOT NULL,
    sodium_goal  DOUBLE PRECISION                        NOT NULL,
    water_goal   DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_goals PRIMARY KEY (id)
);