CREATE TABLE ingredients
(
    meal_id    BIGINT NOT NULL,
    ingredient VARCHAR(255)
);

CREATE TABLE meal
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    category    VARCHAR(255),
    image_url   VARCHAR(255),
    recipe      TEXT,
    recipe_link VARCHAR(255),
    video       VARCHAR(255),
    comments    VARCHAR(255),
    rating      DOUBLE PRECISION,
    external_id VARCHAR(255),
    macro_id    BIGINT,
    CONSTRAINT pk_meal PRIMARY KEY (id)
);

ALTER TABLE meal
    ADD CONSTRAINT uc_meal_macro UNIQUE (macro_id);

ALTER TABLE meal
    ADD CONSTRAINT FK_MEAL_ON_MACRO FOREIGN KEY (macro_id) REFERENCES macros (id);

ALTER TABLE ingredients
    ADD CONSTRAINT fk_ingredients_on_meal FOREIGN KEY (meal_id) REFERENCES meal (id);