CREATE TABLE macros
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    calories DOUBLE PRECISION                        NOT NULL,
    protein  DOUBLE PRECISION                        NOT NULL,
    fat      DOUBLE PRECISION                        NOT NULL,
    sat_fat  DOUBLE PRECISION                        NOT NULL,
    carbs    DOUBLE PRECISION                        NOT NULL,
    sugar    DOUBLE PRECISION                        NOT NULL,
    sodium   DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_macros PRIMARY KEY (id)
);