CREATE TABLE log_data
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    date_time    TIMESTAMP WITHOUT TIME ZONE,
    macro_id     BIGINT,
    water_log_id BIGINT,
    CONSTRAINT pk_logdata PRIMARY KEY (id)
);

ALTER TABLE log_data
    ADD CONSTRAINT uc_logdata_macro UNIQUE (macro_id);

ALTER TABLE log_data
    ADD CONSTRAINT FK_LOGDATA_ON_MACRO FOREIGN KEY (macro_id) REFERENCES macros (id);

ALTER TABLE log_data
    ADD CONSTRAINT FK_LOGDATA_ON_WATER_LOG FOREIGN KEY (water_log_id) REFERENCES water_log (id);