CREATE TABLE macros
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    calories DOUBLE PRECISION                        NOT NULL,
    protein  DOUBLE PRECISION                        NOT NULL,
    fat      DOUBLE PRECISION                        NOT NULL,
    sat_fat  DOUBLE PRECISION                        NOT NULL,
    carbs    DOUBLE PRECISION                        NOT NULL,
    sugar    DOUBLE PRECISION                        NOT NULL,
    sodium   DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_macros PRIMARY KEY (id)
);


CREATE TABLE ingredients
(
    meal_id    BIGINT NOT NULL,
    ingredient VARCHAR(255)
);

CREATE TABLE meal
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    category  VARCHAR(255),
    image_url VARCHAR(255),
    comments  VARCHAR(255),
    rating    DOUBLE PRECISION,
    meal_id   BIGINT,
    macro_id  BIGINT,
    CONSTRAINT pk_meal PRIMARY KEY (id)
);

ALTER TABLE meal
    ADD CONSTRAINT uc_meal_macro UNIQUE (macro_id);

ALTER TABLE meal
    ADD CONSTRAINT FK_MEAL_ON_MACRO FOREIGN KEY (macro_id) REFERENCES macros (id);

ALTER TABLE ingredients
    ADD CONSTRAINT fk_ingredients_on_meal FOREIGN KEY (meal_id) REFERENCES meal (id);